### ISSUE TITLE
Can this do create table as well?

### ISSUE THREAD

**Issue by patagoniahiker** [djsxp/SSDTDeployer#1]
Hi I want to use this and was wondering if it can create table as well?

**Comment by Jishun** [comment]
Hey, thanks for asking.
This package is designed for handling the deployment of a ssdt package (dacpac) in c# function, which is going to do the same as what SqlPackage.exe does, it will deploy the schema contained in a vs database project into the target db. with the option to create the db if not existed. any tables defined in that project will be created/updated, just the same as clicking the "publish" button for that project.  (will support publish profile soon.)
if you don't have tables defined in dacpac, or you just want this lib to create a db without deploying a package, and want to do table creation later on.  check this "TestCreateSqlDb" test method at
https://github.com/djsxp/SSDTDeployer/blob/master/project/DeployerTest/SqlInstanceTest.cs
what it does is: use this lib to remove the existing db if exists, create the new db. initiate a ado.net connection to verify. 
using (var c = new SqlConnection(connectString))
            {
                c.Open();
                c.Close();
            }
Simply call "Create Table xxxx" with a sql command after c.Open(); will do the table creation.

**Comment by patagoniahiker** [comment]
ok thanks :+1:
